### ISSUE TITLE
verify the advisor department association with MCommunity calls

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#10]
This could be a daily process, may implement caching mechanism:

Check whether existing SE advisor is affiliated with athletic department, and pass the boolean value to UI to control whether the Canvas course link will be displayed or not. 

ESB has a API support for MCommunity.

From https://itsjira.umms.med.umich.edu/projects/TLSTEXP/issues/TLSTEXP-3

It will depend on the progress of "esb-utils-python" lib.

**Comment by jonespm** [comment]
Will require getting ESB connected up to Python. Currently it sounds like ESB is mostly used at Michigan with Java apps.

**Comment by pushyamig** [comment]
Yes, earlier mostly were java/Ruby app using ESB. While Java has the ESB-utils supported as needed. This is the right time to have one ESB-utils in python as well. The Java ESB utils were based of [Ruby](https://github.com/tl-its-umich-edu/StudentDashboard/blob/master/server/WAPI.rb) code written for the DASH project

**Comment by DanielDugan** [comment]
@pushyamig I was unable to get to the readme for the MCommunity API through [this link](https://documentation.its.umich.edu/node/336). Can you help me?

**Comment by burgess66** [comment]
Here is another athletic advisor to test with: prhughes

**Comment by jonespm** [comment]
Rolled into #41
