### ISSUE TITLE
As an advisor, I need to filter lists of students...

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#102]
As an advisor, I need to filter lists of students so that I can see only a specific cohort I need to focus on or otherwise focus on one set of students, particularly so that I can find students who are most at risk very easily.

Requirements, ordered from highest to lowest priority:

1. Filter "My Students" list by status (more details on this at bottom)
2. Filter "My Students" list by cohort (show all cohorts that my students are a part of and select which one(s) to see with checkboxes)

Ways to filter by status (checkboxes, all checked by default):
- "Students with no courses this term"
- "Students with no course data for their courses this term"
- "Students with only 1 course this term"
- "Students who have 1 or more red/engage statuses"
- "Students who have 1 or more yellow/explore statuses"
- "Students who have 1 or more green/encourage statuses"

**Comment by jonespm** [comment]
Some of this column based filtering was already implemented in #101. Some of this more custom table based filtering I'm not sure yet how we'd implement but there's *hopefully* a tablesorter demo about how this might be achieved.

**Comment by mfldavidson** [comment]
I'm going to close this since we implemented filtering on all columns except status in 2.5.4 and at this point we aren't sure we need filtering on status--we'll see after we implement sorting on status
