### ISSUE TITLE
Handle newline characters in assignment comments

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#103]
Currently, if there are newline (`\n`) characters in the comments for an assignment, it shows up as "\n" instead of either as a new line or as a space. I would prefer for it to actually reflect a new line if possible, if not, a space. Here is an example:
![image](https://user-images.githubusercontent.com/31591389/56828844-32b5b980-6830-11e9-9cb2-834ccd861204.png)
Whereas it should look like:
``` (2/26/2019) - Remember to use memo formatting
- I think you need to reword and reconsider your energy system
- I also would like to see you be more specific in your description of the energy transfers that occur within the system
- Also, consider the work-energy theorem equation and how that would relate to energy lost, because I do not understand what you are currently saying
- Why are you discussing wind turbines in your discussion of the water storage plant?
- Also, consider the ecological impacts of a system like this"```

**Comment by harryrs** [comment]
Hello, my partner and I are currently enrolled in EECS 481 and are looking to contribute to an open source issue. If this issue is still available, we would like to work on it.
