### ISSUE TITLE
Move develop branch to master, (maybe) delete develop

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#105]
To be in-line with our other workflows, we should delete master, move develop to master and use [trunk based development.](https://trunkbaseddevelopment.com/)

**Comment by jonespm** [comment]
Maybe we can leave Develop for now for Python 3 branch? Then we can bring it up in AWS Openshift to test it before merging. It's looking good but there's probably a few edge cases still.

**Comment by mfldavidson** [comment]
To be honest, I'm not very experienced with different methods of handling branches, but the link about trunk based development sounds like what I've done before which felt like it worked well and makes the most sense.

**Comment by zqian** [comment]
I think we can do the branch change after the Python3 upgrade -- just two more releases (table sorter and filter +Python 3), then we can start with new playground.

**Comment by jonespm** [comment]
Yeah since most of our projects use master as the "source" it's confusing with the ones that use develop. I agree with re-doing it on the move to Python 3. 

I think it's okay to *have* a develop branch but I prefer to release from master as the stable source and have develop be where the develop(ment) work is done.

**Comment by jonespm** [comment]
Nowadays people are actually moving away from [master](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/).

If this project ever got more activity I'd probably just vote to delete master and leave develop as the development branch. If we wanted a branch that's the current release we'd create a new one called something like "release".
