### ISSUE TITLE
Add athletic department advisors to student Canvas courses with Observer role

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#11]
When advisor clicks on the Canvas course link, the SE tool will check whether the advisor has Observer role in that course. If missing, permission will be granted if the advisor is affiliated with Athletic department (via MComm API check)

From https://itsjira.umms.med.umich.edu/projects/TLSTEXP/issues/TLSTEXP-5

Milestone 1, Dec 18th: We will start with predefined list of advisors first, and use ESB util lib to add them to all of the students Canvas courses as observer.
Deliverables in SE dev: based on the given Advisor X, find all student listed in his/her cohort, and add this advisor to all the current term courses for all students. This process will be on daily cron job.

Subtasks:
- [x] for each advisor, find all students he/she advises
- [x] for each student, find all courses in current term
- [x] for each course, check whether the advisor has Observer role in the course; if not, add the advisor to course;
- [x] do the above in a daily cron job

**Comment by DanielDugan** [comment]
Testing with "smrech" this morning

**Comment by jonespm** [comment]
Rolled into #41
