### ISSUE TITLE
Sorting status field (additional work on sorting)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#110]
Sorting statues is going to require a little more custom code than regular sorting so created this as a new issue. I pulled this from #101

> Details about sorting by status:

> Currently, I believe there is no aggregation of student's statuses in courses, only individual statuses per student-course combination. Some sort of aggregation will need to happen in order to sort by status
> I would like to sort by the AVERAGE status--add up all the statuses they have and divide by the number of statuses. The reason for this is that it will sort the students who are the most "at risk" to the top and will not matter how many classes a student is taking. Would like students with no courses or no statuses to bottom.

**Comment by jonespm** [comment]
So there's some more info that was posted here.

https://github.com/tl-its-umich-edu/student_explorer/issues/101#issuecomment-487173549

Trying to think of the best way to sort. 
I think if a student has like lots of reds and a few greens it should sort above someone that has 1 yellow? Maybe make reds worth 10, Yellows worth 5 and Greens worth 1? Up for any suggestions. 

This is an example of that. It counts the "no value" as 0, but it counts it (currently) counts those against the mean and maybe that's not a good idea.
![image](https://user-images.githubusercontent.com/27447/59464992-dc103900-8df7-11e9-8752-a5a37fe702d6.png)

**Comment by mfldavidson** [comment]
I would count "no value" as Null (i.e. not count it against the mean) for sure. I think your recommendation about making the values worth different amounts is a great idea. Once implemented we can test with users and shouldn't be hard to change the numbers if this behavior is not as they expect.

**Comment by jonespm** [comment]
Okay I'll try that next week and see how it works. 

So someone that had 3 reds = 10. 
Someone that had 5 reds, 2 yellow = 8.57

Doing an average it seems like anything not a red will always drop the value. I wonder if it better to just sum them up? Or maybe we need some different algorithm considering each color independently? Maybe like a [weighted sum](https://en.wikipedia.org/wiki/Weighted_sum_model)?

Say reds are 0.6, Yellows 0.3, Greens 0.1
(Reds) 5 * 0.6 + (Yellows) 2 * 0.3 + (Greens) 0 * 0.1 = 3.6
(Reds) 3 * 0.6 + (Yellows) 0 * 0.3 + (Greens) 0 * 0.1 = 1.8
(Reds) 0 * 0.6 + (Yellows) 3 * 0.3 + (Greens) 2 * 0.1 = 1.1

That *seems* reasonable. . . I wonder if it'd be too confusing though. ;)

**Comment by mfldavidson** [comment]
I'd like to keep it simple so advisors can understand it pretty easily. Let's go with the average as discussed and see how advisors feel about it, if it meets their expectations. My gut says that anything not a red SHOULD drop the value, so it may be ok.

**Comment by jonespm** [comment]
This is how it sorts dropping the empty values (The text there is just for testing purposes)

I think I'd have to implement the code for weighted sum to improve this, that would put 2-3 reds above one with just 1 red.

![image](https://user-images.githubusercontent.com/27447/60824787-422e7880-a178-11e9-82bf-0785714bd748.png)

**Comment by mfldavidson** [comment]
I don't think I necessarily agree that the one with two reds SHOULD sort above the one with only one. If a student is in only one class, and they're really struggling in that one class, that seems like that . could be more of a concern than a student who is in 5 classes and is doing well in 2, middling in 1, and struggling in 2. I'd like to test it is as.

**Comment by jonespm** [comment]
Cool, I put in a PR for this idea. Since this is now Python 3 the code was even more straightforward to the statistics package.

**Comment by mfldavidson** [comment]
This is looking great! Two changes after my own round of testing before I pass along to advisors for testing:
1. Can we reverse the sort order so that the first click sorts descending instead of having to click twice to get the reds at the top? (does that make sense?)
2. After seeing the way it handles the grays/no values, I'm thinking we may need to assign a very small number to those ones so that they sort above students with no courses at all, but below students with ANY courses that have data. Something like 0.5?

**Comment by jonespm** [comment]
1) Yeah, setting an initial sort direction [looks easy](https://mottie.github.io/tablesorter/docs/example-options-headers-order.html) and nothing I configured. Are you fine doing it for all columns only want it for this status field one? 

2) It's at 0 now, just dropping from the list if it's zero because it skews off the average. Like if you have a Red, Green and Grey it becomes (10+1+0) / 3 = 3.6, which is higher than one without the grey. . . I feel like we'll have to go down the weighted average road. Though looks like [Numpy can do it. ](https://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html)

Maybe just have use weights in here, (count of) reds = 50%, yellows = 30%, green = 15%, Grey = 5%?

**Comment by mfldavidson** [comment]
1. Just the status column. Generally if an advisor wants to sort by status they will be doing it to see their most at risk students first, but right now they'd have to click twice to do that. Clicking once sorts the students with no courses/no course data to the top, which is not helpful to anyone.
2. Let's discuss in person, I'm not sure if I'm following.

**Comment by jonespm** [comment]
1) Cool I can do that 
2) Yeah, I just wanted the grays to be worth less in the denominator. Maybe the math is more back to just a simple sum again . . . 

#Reds * 50 + #Yellows *30 + #Greens * 15 + #Greys * 5

3 Reds 2 Yellows = 150 + 60 = 210
1 Red 1 Yellow = 80
1 Red = 50
1 Green, 3 Greys = 15 + 15 = 30
1 Yellow = 30

**Comment by mfldavidson** [comment]
I understand what you said about skewing the average now. In general, I don't think the grays should be taken into account if the student has any other courses that have data. For example, the concept that you suggested would put a student with 1 green and 3 grays with the same value as a student with 1 yellow, but an advisor would almost certainly consider the student with 1 yellow to be more "at risk" and thus should sort higher than the student with 1 green and 3 grays.

Is it too complicated to do something like: (please excuse my bizarre pseudocode)
- if student has at least one of [red, yellow, green]: calculate by the average we've been doing
- elseif student has ONLY grays (one or more): assign a value of .05 to each gray and sum it so that more grays sort higher
- else: assign a value of 0 (should only apply to students with NO courses)

**Comment by jonespm** [comment]
Yeah, I can try that, I'll let you know what there's a PR for it.

**Comment by mfldavidson** [comment]
So far all advisors who have tested have reported that the current status sort makes sense. I'll call this good!
