### ISSUE TITLE
There are too many entries on the /classes/ page and not very useful

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#115]
There's a list in SE /classes/ that has every course that ever existed in the system. (Over 100000) This list feels mostly useless to me and not working right with the new pager.

I think we either need to 
- Remove this url entirely so nobody hits it
- Put some limit on it, either 
  - X most recent classes (sorted by ID), say 2500? Probably like `SELECT * FROM DM_CLASS_SITE WHERE src_sys_key = 5 ORDER BY CLASS_SITE_KEY DESC;`
  - Only classes matching the current year (currently more than 5000)

~3000-5000 seems to be the "safe" limit for the pager.

**Comment by mfldavidson** [comment]
Please remove the URL entirely. This is something we may want to explore reactivating in the future with a limit such as you discuss, but for now, nobody is using it. I checked the analytics.
