### ISSUE TITLE
As an advisor, I expect name sorting to sort by last name then first name...

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#118]
...so that I can find students in the same order that most other lists of my students (last name sorting is usually default).

The way sorting is working with the way we implemented #101 is that it sorts by first name since "First Name Last Name" is one string. The default sort when folks first arrive on the page is first by Last Name, then by First Name. They can't get back to this sort once they sort by anything else. However, since most student lists default sort by Last Name then First Name (like SE default), it is preferred to be able to get back to this as well as for name sorting to default to this.

DM_STDNT has first and last name as separate columns so the joining into one field is being done by the application.

I will offer most desired way to implement this, and a second choice understanding the most desired may be too difficult to implement:
1. Separate First Name and Last Name into separate columns, and if someone sorts by Last Name it primary sorts by last name and secondary sorts by First Name (instead of just sorting by Last Name which I know is what it would do with how we have currently implemented) and vice versa (sorting by first name also secondary sorts by last name). I think it is important to allow sorting by first name OR last name if someone wants it, and this is the only way I can think of to allow both. However, simply splitting first name and last name into separate columns will mean that people with the same first name or same last name will be sorted in what will feel to users like unexpected ways. For example, if you have Alan Johnson, Betty Johnson, and Zhen Johnson, and you sort by last name, you'd expect Alan to be first and Zhen to be last, but that's not necessarily the case if it just sorts by last name and doesn't have a secondary sort by first name.
2. If 1 is too hard, change the way the Student Name column is produced from First Name Last Name to Last Name, First name so that at least the way the sorting works will essentially be primary sort by last name, secondary sort by first name.

**Comment by jonespm** [comment]
1) Would be more work and currently I'm also putting the uniqnames as well incase two people have the same first and last name so you'd probably need a third column. (Which is very possible)

2) This option is easy and would immediately fix the sorting

3) As a third option I believe this library supports an attribute "data-text" and we can put the order we want it to sort into that field, and leave the display whatever we'd like!

**Comment by mfldavidson** [comment]
1. When you say you're putting the uniqnames as well, what do you mean by that? Where are you putting them? (as an aside, I was just thinking of creating an issue to add a uniqnames column. Nobody has requested it, to be honest, but I'll explain why separately.)
2. Good to know!
3. Off the top of my head I do not think this would be confusing but I'd want to test with users.

As an aside, because M-Community sorts by first name, it may be more desirable than I was thinking to have the ability to sort by first name as well. There's an advisor who brought up the last name sort issue and she also pointed this out. Thus, I'm curious how much more work option 1 is. I don't think sorting by name in general is the most important thing, so I don't want us to put TOO much time into this, but I do think that ONLY allowing sorting by first name is not acceptable (I should have thought of this, my bad) since once the advisor sorts by anything one time, they can't get back to the original default sort by last name. I'll try to chat with some advisors to get a sense of importance of sorting by first name.

**Comment by jonespm** [comment]
1) On the advisors list it is, I guess on the students list it isn't (but probably should be)
![image](https://user-images.githubusercontent.com/27447/60605838-3dd51a80-9d88-11e9-925a-fbf741a3a07e.png)


We *could* do 3 columns but this would be a little more work

**Comment by jonespm** [comment]
Okay so it actually didn't take that long if this is what you wanted, this is what it looks like

![image](https://user-images.githubusercontent.com/27447/60726524-c929e980-9f09-11e9-95e6-1377a231ed9c.png)

![image](https://user-images.githubusercontent.com/27447/60726599-f080b680-9f09-11e9-8abb-8d3433606594.png)

**Comment by mfldavidson** [comment]
I think this works as best it can but I'd have to test to be sure. Thanks!

**Comment by mfldavidson** [comment]
Sorry about open/close that was an accident. Advisors who have tested the split into first, last, uniqname are pleased, no changes suggested. I'll call this good!
