### ISSUE TITLE
Caching for Student Explorer

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#122]
This may need to be something we work on for AWS Openshift.

We noticed that there was 3-4 seconds additional time on each request when using the new environment, possibly related to the database calls to Oracle. 

I researched looking into [Django Cachalot](https://django-cachalot.readthedocs.io/en/latest/ ) with Redis to try to improve performance. This is something we should look at and possibly measure if it really is slower. 

Probably also enabling the Debug-Toolbar might uncover the difference as well.

**Comment by jonespm** [comment]
Some guides
https://realpython.com/caching-in-django-with-redis/
https://code.tutsplus.com/tutorials/how-to-cache-using-redis-in-django-applications--cms-30178

**Comment by jonespm** [comment]
This actually seems like it might be easier in Student Explorer because I believe every view is the same for every user that comes into the page. We don't have to implement much "per-user" caching like might be needed in applications like MyLA.

**Comment by mfldavidson** [comment]
That is correct, the view is the same for every user

**Comment by jonespm** [comment]
Great, this is how I'm implementing it, should be much faster than I thought!

**Comment by jonespm** [comment]
Doh, the problem is that even though every view is the same for every user, at the top of the template it has a everyones username. If we cache the entire view it will also cache this part. 

So because of this I think rather than having an easy system wide view cache we'll have to just have a per user view cache (which will improve the speed of the system slightly for the user, but not as much as it would) or would have to look into caching something else like the database calls rather than the views. 

The big thing to test with the view cache is if you have 2 users on two different browsers (or incognito windows) that they don't see each others name in the top right when navigating on the same students, advisors or class pages.
