### ISSUE TITLE
Add tracking (log  message and event in db) for cohort deletion 

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#13]
UI instructions:

1. login as admin user to Student Explorer tool
2. click on the login name in upper right corner, select "Manage" choice
3. click on Cohorts
4. If there is no cohort listed, click on "Add Cohort" to add one
5. select a cohort and click on the "Delete" link, and confirm on the popup window.

Currently, if a cohort is deleted (step 5 above), there is no tracking of the deletion inside either app log message nor database tables.

The task is to add both log info message, and also insert a record inside "tracking_event" table for the cohort deletion.

**Comment by DanielDugan** [comment]
Sounds good.
It looks like I need to:

1. Write a handler using the Django signals library that both pushes a "log info" message to the app log and event DB (https://docs.djangoproject.com/en/2.1/topics/signals/)

2.Add that handler to our events tracking model (https://github.com/tl-its-umich-edu/student_explorer/blob/develop/tracking/models.py)

3. Route that handler to trigger on a cohort deletion event

Does that look right?

**Comment by jonespm** [comment]
Yup, that sounds like it. It sounds like signals are preferred for this over [overriding these methods](https://docs.djangoproject.com/en/2.1/topics/db/models/#overriding-predefined-model-methods
) on the model. Probably on the post delete so you can be ensured it's actually deleted.

There's already a method "create_event" in the utils that could probably be used over the model directly. 

MyLA uses a library "[Pinax EventLog](https://github.com/pinax/pinax-eventlog)" which I'd like to switch SE over to someday so they're consistent and good news is they look super similar. The docs for that suggest this similar pattern.

(We're on 1.11 Django but I believe these are unchanged)

**Comment by jonespm** [comment]
@DanielDugan Mentioned that the two scoops book recommended the "overriding these methods" as the way to go over signals. https://docs.djangoproject.com/en/2.1/topics/db/models/#overriding-predefined-model-methods.

https://docs.djangoproject.com/en/1.11/topics/db/models/#overriding-predefined-model-methods

I'd probably just go with that, override the delete method on the cohort model to add in the tracking.

**Comment by DanielDugan** [comment]
Need to sort out user still, but it is now logging cohort deletion in the db.
https://github.com/tl-its-umich-edu/student_explorer/pull/51
