### ISSUE TITLE
Remember last sort

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#130]
While testing the new sorting functionality, we got this really helpful feedback from an advisor:
My only suggestion is to ask if there is any way for it to keep your last sort setting as you click in and out of individual students.  For example, I sorted by status, and [specific student] was the student at the top of the sort, followed by four others with statuses for [this term].  I checked out [student]'s data, but when I went back to my full list to find the next student to check on, my list wasn't sorted by status any more - it had reverted back to a last name sort.  This is not a real problem, I just clicked on status to sort again, but if my goal was to check statuses on all my students, it was annoying to have to sort again by status every time I clicked in and out of an indiv student record.  Would there be any way to have it keep your last sort setting as you click in an out of indiv students (if others agree that would be more efficient for how they work)?

**Comment by jonespm** [comment]
Hmm, it does look like there's an option.

https://mottie.github.io/tablesorter/docs/example-widget-savesort.html

This would persist only until the local cache is stored and only on that computer but it looks like it would do this. To go beyond we'd have to persist some settings to the server which would be more effort.

**Comment by mfldavidson** [comment]
I am not sure if I see a need to go beyond local cache on that computer so this seems fine. We may have to remove the default ordering by last name in order for this to work. Is there a setting in tablesorter to set a default order? Right now our default ordering (unless you changed it and I didn't notice) is handled on the backend.
