### ISSUE TITLE
Change redirect for users without cohorts and create advisors/<advisor> route at account creation

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#139]
Related to #86 . Currently, when an advisor doesn't have a cohort (as is the case for many of them, particularly new users), they are redirected to /advisors. This has been confusing for many of them because it shows a list of advisors and they think that it is a list of people who have access to Student Explorer, and since their name isn't on it, they think they don't have access. Taking them to their own cohort page (with additional text on that page that will be added in another issue) should resolve this confusion. An additional reason to make this change is that /advisors is being removed from header navigation and redirects (in another issue) because it is not relevant to end users, so this change is necessary as a part of that.

Currently, the advisors/<advisor uniqname> route isn't created until an advisor has at least one student assigned to them in a cohort. This is why a redirect to /advisors is necessary right now--because there isn't an advisors/<advisor uniqname> page to direct to. However, this appears to be created with the assumption that only admins would not have a cohort, but this is no longer true. Thus, we will now want this route to exist as soon as an advisor's account is created. Then, we need to change the redirect so it doesn't redirect users to /advisors ever.

The redirect is in https://github.com/tl-its-umich-edu/student_explorer/blob/develop/seumich/views.py lines 162-169

Acceptance criteria: all users have an advisors/<advisor uniqname> route created at the time of account creation, regardless of whether or not they have ever had a cohort. When advisors navigate to https://studentexplorer.ai.umich.edu/ ('/') they land on the advisors/<advisor uniqname> page instead of /advisors.

**Comment by mfldavidson** [comment]
Per conversation at today's release meeting, it is too challenging to create the routes dynamically because their creation is part of an ETL process we don't manage that comes from the cohort files (the .dat files downloaded in management). Instead, we will investigate whether we can redirect to /about but include a banner at the top (BENEATH THE HEADER) that only shows if the user is redirected via Index view. This message should be minimal and only bounce the user to one info source (as opposed to bouncing them to one source that bounces them to another source, etc...bad UX!). I'm currently thinking through the language and redirects and will come back ASAP with some thoughts.

**Comment by mfldavidson** [comment]
Lindsay on the UX team had an idea for handling the redirect for users without a cohort and I think it's possible but want to confirm. Can we make a page that is something like /advisors/nocohort/ that mimics the structure of the My Students page by having the advisor's name in red at the top but instead of the student list it shows the message (or similar message, I will edit a bit) that is in #140 AND has a big ol' search bar right there as well as in the header, since we know that folks that end up on this page will either want to 1) set up a cohort (for which there will be info) or 2) search for a student.

**Comment by mfldavidson** [comment]
(I'm working on changes to documentation to ensure that the instructions for cohorts don't bounce them around too many times)

**Comment by ssciolla** [comment]
> Can we make a page that is something like /advisors/nocohort/ that mimics the structure of the My Students page by having the advisor's name in red at the top but instead of the student list it shows the message (or similar message, I will edit a bit) that is in #140 AND has a big ol' search bar right there as well as in the header,

I don't know if it's possible to actually use a `/advisors/nocohort/` route, since `/advisors/` is already established as a pattern, but I think it is possible to do what you're suggesting. Getting the user's name might be a bit tricky, but seems do-able. I still think it would be preferable from a code design standpoint if we could find a way to get the advisor in the Oracle Mentor table, and then do some template magic to present the text and the search field you want. If we don't think that's do-able, I can go down this route.

**Comment by mfldavidson** [comment]
Totally makes sense, I hadn't thought about the pattern issue. It can be anything so long as it makes vague sense to the user. /advisornocohort maybe? I assume that getting the name is possible because we're getting the uniqname to show in the upper right in the header, but I know those are separate templates. I'll check on getting the advisor in the table but per our previous discussions I am not optimistic.

**Comment by mfldavidson** [comment]
From mapping doc, we were correct that DM_MNTR is created based on unique values from TLA_StudentCohortMentor_USELAB.dat.

> • Performs lookup against PS_M_CC_ORDRNAM_VW based on MentorUniqname to get the first name / last name values
> 
> • Data sourced from one source:
> 1. TLA_StudentCohortMentor_%.dat (see below SQL example)
> "SELECT DISTINCT U.EID,
>                 O.FIRST_NAME,
>                 O.LAST_NAME
>                 O.EMPLID   *****Added June 2013 - Steve Lonn Requested*****
> FROM TLA_StudentCohortMentor_%.dat TLA
>   INNER JOIN heprod.ps_m_cc_pdname_vw P ON upper(TLA.MentorUniqname) = P.CAMPUSID
>   INNER JOIN heprod.PS_M_CC_ORDRNAM_VW O ON P.emplid = O.emplid"

Based on the way BG_STDNT_CHRT_MNTR which is the mapping table between students, cohorts, and mentors/advisors loads, I don't think there's any way to just get a mentor in there without mapping to a "student":

> • Table will be loaded based on the relationships between students/cohorts/mentors in the TLA_StudentCohortMentor_%.dat file and will be truncated/reloaded during each run of the ETL.
> • If the MentorUniqname value in the source record is blank, load with a -1 MNTR_KEY
> • The RCD_LAST_UPDT_DT_KEY will be sourced from a date attribute portion of the filename

Thus the only thing I can think to do is to map them to a "fake" student. However, looking at how a student can still be added to a cohort without a mentor in second line of above blurb, it gave me an idea...could we somehow have a cohort that just always exists that, if mentors aren't in any cohorts, they get added to (and REMOVED from once they have a cohort?) and mapped to the STDNT_KEY of either -4 or -1?
![image](https://user-images.githubusercontent.com/31591389/65694994-baecf480-e044-11e9-93fa-d3bb29d8f853.png)

**Comment by mfldavidson** [comment]
Mapping to a fake student worked--[see example with Sam's account](https://studentexplorer.ai.umich.edu/advisors/ssciolla/). Because STDNT_UM_UNQNM values for "fake students" (STDNT_KEY<1) are in mixed upper/lower case and the cohort creation process standardizes all uniqnames to uppercase, no matter which "uniqname" of the fake students we enter, it will always end up mapped to -2 NotHappen. -2 NotHappen is the value that is chosen if a match isn't found in DM_STDNT for a student uniqname entered in cohort creation. So, for example, if we enter NotApplic as a student uniqname in cohort creation, it will be changed to NOTAPPLIC, and thus will not be matched to -4 NotApplic, so then it will be mapped to -2 NotHappen as default.

Now we need to discuss--would the best thing to do to be to create a placeholder cohort that all new users are added to, and automatically map them to some bad uniqname value that definitely will never be a real uniqname (maybe something longer than real uniqnames to be safe?)? This seems like a dangerous workaround if we ever accidentally delete the cohort, but otherwise would work. We don't have to remove the student-cohort-advisor mapping either if we change the queryset to filter by student_key>1 which we should do anyway. That will get rid of the Not Happen Yet situation.

**Comment by mfldavidson** [comment]
Ok we are changing the plan AGAIN and just changing the code in https://github.com/tl-its-umich-edu/student_explorer/blob/develop/seumich/views.py for AdvisorView to just not return a 404 and pass the advisor context as the user's uniqname. Idea from @jonespm so bother him if you have questions.

**Comment by mfldavidson** [comment]
Testing passed! Tested the following:
- Added one of our colleagues who has never had an SE account or a cohort as a user in test and it worked--route created
- Deleted the above account and it worked--route doesn't exist anymore
- Navigated to a /advisors/randomuniqnamethatdoesn'texist/ page and it worked--said "no advisor profile found
