### ISSUE TITLE
Add the date the data was updated to header/footer

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#15]
This was created from issue TLPSO-464

Queries the relevant table in Student Explorer (SE) database the contains the date the database was last updated. This should help identify issues related to failures in database updates in SE. Show the last updated timestamp on header or fixed footer.

select LOAD_DT 
from CNLYR002.LRNG_ANLTCS_STAT
where DW_DATA_NM = 'Student Explorer Daily Tables';

20-NOV-18

**Comment by zqian** [comment]
The last updated timestamp of couple of data resources are captured inside CNLYR002.LRNG_ANLTCS_STAT table. Need to surface it in the Student Explorer UI:

select * from CNLYR002.LRNG_ANLTCS_STAT
DW_DATA_NM EXTRCTP_DT LOAD_DT DW_OWNR_NM
Student Explorer Daily Tables	22-OCT-18	23-OCT-18	cnlyr002
LARC Data Set	25-SEP-18	25-SEP-18	cnlyr002
Student Explorer Weekly Tables	21-OCT-18	21-OCT-18	cnlyr002

**Comment by DanielDugan** [comment]
Are we looking to do this in base-Django, or are we open to including other dependancies?
Example:
https://github.com/hirokiky/django-reportmail

**Comment by jonespm** [comment]
@DanielDugan This is in ITS Jira https://itsjira.umms.med.umich.edu/browse/TLPSO-464 . Contact @zqian if you can't access it.

Using a library like this seems fine but this one hasn't been updated in 3 years and there's a PR to "update" it which hasn't been merged. 

I might just avoid this and use something simpler. For instance in this PR I added just a basic email function to send up a message.

https://github.com/tl-its-umich-edu/unizin-sis-validation/commit/9b9355e199ff3a3b4eb11cc87e02e738a37ca033

If you find a library that is updated/supported we could use that.

**Comment by jonespm** [comment]
The code above is currently sending email daily. 

I believe it's flagged as "safe-enough" as it sends through a verified relay. The messages look to be DKIM signed and permitted, so won't be an issue. There's an example to setup a local SMTP there for testing, but yeah just trust that it "will" work if configured. 

I made the Subject configurable in another commit. There may be more headers that could be optionally set but doesn't seem necessary.

**Comment by jonespm** [comment]
I would look at the commit on https://github.com/tl-its-umich-edu/my-learning-analytics/pull/237 for some code about adding to the templates.

**Comment by DanielDugan** [comment]
Investigating.

Student explorer does not appear to have a base.html template.

https://github.com/jonespm/student-dashboard-django/commit/8cd8e77356893eb27b93c35e4171b558328c96f3

Am I missing it, or was it excluded?

**Comment by jonespm** [comment]
It looks like SE's base template is at
https://github.com/tl-its-umich-edu/student_explorer/blob/develop/student_explorer/templates/student_explorer/index.html

**Comment by DanielDugan** [comment]
Incorporated feedback button into footer div
Set footer to "fixed". 
Intend to move "reagents" text to be more responsive (thinking "Text-align:center", but that didn't work)

<img width="540" alt="screen shot 2018-11-20 at 4 16 10 pm" src="https://user-images.githubusercontent.com/7157421/48803376-c0b8d180-ecdf-11e8-921d-93574690b4c5.png">

**Comment by zqian** [comment]
Since the "11/29/2018" is hard-coded for now, next step is to get the value dynamically.

**Comment by zqian** [comment]
Assigning this for Dan to test on dev:

 https://dev.studentexplorer.openshift.dsc.umich.edu/

**Comment by burgess66** [comment]
PRT testing complete
All looks good.
Proceed with release
