### ISSUE TITLE
Nav bar rearrangements

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#151]
## Summary of Changes
Details about the changes are listed below in the corresponding section.
1) Make the Student Explorer logo/name link to /about instead of /
2) Move search bar to the left so it is just to the right of Student Explorer logo/name
3) Remove "Advisors" (/advisors) link from header and instead put it in the drop-down that appears under user uniqname
4) Move the remaining links in header ("My Students" and "Resources & Support") to the right
5) Add "About" link in between "My Students" and "Resources & Support"

Nav will now be ordered like:
Student Explorer Logo | Search Bar | (space) | My Students | About | Resources & Support | uniqname

## 1. Logo Link
Users expect clicking the logo in the upper left to take them to a "homepage" of sorts. Sprucing up the /about page allows us to link to this page, which is as close to "home" as we have, instead of the My Students page, which could be confusing.

## 2. Search Bar Move
Moving the search bar to the left makes it more visible and important and separates it from the other nav links that we are moving to the right.

## 3. Advisors Link Move
End users think the /advisors page shows people who have access to Student Explorer, but it doesn't. It shows the list of links for every advisor's "My Students" page. This is mostly just useful for admins. To minimize this end user confusion, we would like to remove the /advisors page from the top nav bar. To ensure it doesn't get "lost" for admins who need to use it, let's put a link to it just above "Manage" in the drop-down from uniqname in upper right. The link should have the same display logic as "Manage" (i.e. only admins see it). The link should be named something like "Advisor Views" to describe what it is (originally said "Advisors with Cohorts," but assuming the sneaky add-in of advisors without cohorts to DM_MNTR works, it will end up being all advisors anyway). To be clear, we do NOT need to change permissions for /advisors. If someone navigates directly to it, that's ok.

## 4. Header Links Move
The remaining nav links in the header are "My Students" and "Resources & Support." These should move to the right so that they are just to the left of the uniqname dropdown.

## 5. About Link Addition
Now that we have a nice About page, let's add it to the header nav so people can find it!

**Comment by ssciolla** [comment]
Issue has been resolved, and the improvements have been QA tested.
