### ISSUE TITLE
test_student_class_site_view is failing

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/student_explorer#162]
One test in `seumich/tests.py` seems to be failing: `test_student_class_site_view`. My cursory look at the code did not provide any clues as to what might be going on.

![Screen Shot 2019-10-03 at 11 03 41 AM](https://user-images.githubusercontent.com/35741256/66138973-91e0dc80-e5cd-11e9-8da9-5f4530321909.png)

**Comment by jonespm** [comment]
This might be improved by merging #160 and removing cachalot
