### ISSUE TITLE
Add a :delegated option to docker-compose for local directories to improve performance

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#177]
I posted about this in MyLA but was experimenting here. Wanted to see if you had any feedback on this and/or if you've (@ssciolla) felt any slowness with development on either of these applications lately.

**Comment by ssciolla** [comment]
I'm a little unclear what slowness you might be referring to? What's the advantage of moving to `docker-sync`? Can you point me to a resource/article describing this?

**Comment by jonespm** [comment]
Oh sorry, I posted a little more here:
https://github.com/tl-its-umich-edu/my-learning-analytics/issues/767

It just feels slower to me ever since we enabled mounting the local file system. I also feel like I've heard Pushyami talk about it being a little sluggish. A number of articles I've read just say that having the files locally are 50%+ slower than having them in the container.

**Comment by ssciolla** [comment]
Oh, I see. I haven't noticed too too much sluggishness on either application, but when working on the downloader project (which we talked about a little bit), I was starting to suspect that constantly writing to the SQLite database file in a volume was really hurting performance. I still want to try moving the SQLite database in and out of the container before and after execution (using a `.sh` script) to see if less writing to the volume improves the situation.

**Comment by jonespm** [comment]
Yeah, hmm, the MySQL files are stored on the container host too. I don't know if database files like this would be very easy to keep synced up with the container. Maybe it's not as big a deal as it seems but I for sure noticed this same problem on Windows. The only way I can develop on that is in a Linux Virtualbox.

**Comment by jonespm** [comment]
On MyLA we just marked the local drives as :delegated. So this is all we'd do here
For the app
`      - .:/usr/src/app:delegated`
For MySQL
`      - ./.data/mysql:/var/lib/mysql:delegated`

**Comment by jonespm** [comment]
I also noticed that the MySQL wasn't mounted locally, we should probably do this for this app.

**Comment by jonespm** [comment]
Not something we need to do anymore
