### ISSUE TITLE
Investigate caching at intermediate levels

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/student_explorer#181]
Thus far we have successfully implemented and improved performance by caching templates at the lowest level (i.e. leaf nodes, that do not `include` any other templates). However, we have noted that intermediate templates (those that `include`a leaf node) like `advisor_detail` and `student_list` employ `if [condition]` checks that will require additional SQL queries.

One solution would be to move as many conditions as possible to the leaf node templates; I have implemented such a solution in PR #179 to try to solve issue #175. However, in the interest of making the leaf node templates (specifically `student_list_partial`) less convoluted and isolate case handling at higher levels, it would be nice to keep the intermediate templates as they are. Thus, we could at least explore the possibility of caching at one level higher.

**Comment by ssciolla** [comment]
@jonespm, I made some quick changes and moved caching up a level, and it seems to be caching without hiccups. See my work in [this commit](https://github.com/ssciolla/student_explorer/commit/94d8c48d68c2653c3fde8a84b6dbedcc0e67c014).

**Comment by jonespm** [comment]
Cool that commit looks good, open a PR for that and close the other one.
