### ISSUE TITLE
SAML entityid should be configurable

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#187]
This is defaulting to a entityID that includes the domain name and metadata. This should be configurable to use something like SAML2_ENTITYID for instance as a property.

If that value isn't defined it can default to being the value currently in the code

https://github.com/tl-its-umich-edu/student_explorer/blob/824aa7075917ea88e13ed127acb71164ea103fea/student_explorer/settings.py#L209

This is from this documentation where it says

> it is strongly recommended NOT to use the physical hostname of a server running Shibboleth as the entityID

https://wiki.shibboleth.net/confluence/display/CONCEPT/EntityNaming

**Comment by ssciolla** [comment]
I'm resolving this, since we did make the change although we're still figuring out whether what kinds of `entityIds` we can use.
