### ISSUE TITLE
'About' tab doesn't show as active in navigation when accessed via link in advisor_without_students template

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#189]
https://github.com/tl-its-umich-edu/student_explorer/blob/develop/seumich/templates/seumich/advisor_without_students.html

My bad on not noticing this during testing but the 'About' tab in header nav isn't showing the color that we use to indicate it's the active tab when 'About' page accessed via the link we added for advisors without students. Upon first glance through, I suspect that we need to remove the trailing '/' from the link in the advisor_without_students template.

When 'About' accessed via clicking on 'About' in nav bar, by clicking Student Explorer logo in upper left, or navigating directly to it:
![image](https://user-images.githubusercontent.com/31591389/67896477-d0b57400-fb32-11e9-906d-0b1ae2867aea.png)

When 'About' is accessed via clicking on the link in advisor_without_students.html template (see line 29 in template):
![image](https://user-images.githubusercontent.com/31591389/67896588-09ede400-fb33-11e9-9e51-9926831c39d1.png)

**Comment by susannesheng** [comment]
Hello, I am in EECS 481 and I am looking to contribute to an open-source project. If possible, I would like to work on this issue.

**Comment by zqian** [comment]
@susannesheng yes, please self-assign and claim the issue!
