### ISSUE TITLE
Student Explorer sends email alert when advisor accesses bookmark for prior term courses

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#195]
Student Explorer only displays course for current term. When advisor attempting to access a prior term course, maybe through a bookmark, system generated the following error message and sent out alert email:

Internal Server Error: /students/<advisor_id>/class_sites/<class_id>/

DoesNotExist at /students/<advisor_id>/class_sites/<class_id>/
StudentClassSiteStatus matching query does not exist.

Request Method: GET
Request URL: http://studentexplorer.tl.it.umich.edu/students/<advisor_id>/class_sites/<class_id>/
...

The desired fix would be catch the attempt as log warning, instead of sending out email alert.

**Comment by mfldavidson** [comment]
I would prefer to continue receiving email alerts unless we change the template to better explain to them what is going on

**Comment by mdhvprasad** [comment]
Hi @zqian @mfldavidson , I am currently enrolled in EECS 481 at umich, and for our project my partner and I have to make an open-source github contribution. Would it be ok if we worked on this issue / is it still open? Thanks!

**Comment by mfldavidson** [comment]
Hi @mdhvprasad I think we need to think some more about what we want to do about the issue @zqian raised--can you take a look at some other issues?
