### ISSUE TITLE
Text on student class site page gets crowded on smaller viewports

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#212]
In StudentClassSiteView if you are viewing the page on a smaller viewport before the tablet breakpoint (such as on your laptop instead of on a big monitor) the following text crowds:
- week names in the weekly vizs
- long assignment names crowd due date

![textcrowding](https://user-images.githubusercontent.com/31591389/73082193-fd113000-3e96-11ea-9652-47d29b41d652.png)

Need to add padding, change breakpoint, or something to avoid this

**Comment by jonespm** [comment]
* Could change the Week Label to just have numbers and have some initial label that says Weeks.
* For the text, could possibly wrap to a new line

**Comment by mfldavidson** [comment]
Addressed by PR #236
