### ISSUE TITLE
Move manage cohort buttons to top of page

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#215]
The following buttons currently appear BELOW the list of cohorts on the cohorts page:
- Add Cohort
- Download TLA_Cohort_USELAB.dat
- Download TLA_StudentCohortMentor_USELAB.dat

I would like to move these above the table so I don't have to scroll to get to them. Super minor I know. But it will make a big difference for me.

**Comment by jonespm** [comment]
This will probably happen along with #214
