### ISSUE TITLE
Remove extra period on About page

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#217]
Extra period at the end of the Access paragraph on About page

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31591389/74467563-4980d780-4e67-11ea-8345-5d50ea8a9414.gif)

**Comment by jonespm** [comment]
If you kept zooming in it'd be back to one period. But what happens if you zoom in beyond that? Do you get to into sub-period space? What are periods really made of? This gets deep!

**Comment by mfldavidson** [comment]
75% of my sense of humor is just zooming in on things I just think it's hilarious

**Comment by mfldavidson** [comment]
FWIW we actually released this with the emergency fix last week 2.7.1
