### ISSUE TITLE
Remove Usage of API_UTILS

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#234]
This either should be removed or we should add this via requirements.txt

#### Currently on:
+ **Commit**:  9fcb7e7006f156ce2c727a54fa783d39c1011645
+ **File**:    [Dockerfile](https://github.com/tl-its-umich-edu/student_explorer/blob/9fcb7e7006f156ce2c727a54fa783d39c1011645/Dockerfile)
+ **LineNum**: [24](https://github.com/tl-its-umich-edu/student_explorer/blob/9fcb7e7006f156ce2c727a54fa783d39c1011645/Dockerfile#L24)

**Comment by ssciolla** [comment]
@jonespm, should we also remove the `python-api-utils` installation and ditch `cron.py` in 2.8?

**Comment by jonespm** [comment]
I think this is the only file that uses this. What do you think @zqian?

cron.py only existed to support the action of adding observers to a course. Leaving it there requires us to still have django-cron and python-api-utils dependencies. I'm fine removing it if Zhen is. 

It might take a little more cleanup to the start script, the settings.py and the dockerfile to completely remove this.

**Comment by zqian** [comment]
Agreed. The add observer job is never deployed. It is OK to remove the cron.py and update dependencies. Thx!

**Comment by zqian** [comment]
tested from the SE test server. The SE tool behaves fine after the code update and related env variables removed from the settings.
