### ISSUE TITLE
update needed for Service Manager field in about.html page

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#249]
The Service Manager for Student Explorer has transitioned from Maggie to Hema now. This hard coded value in the [about.html](https://github.com/tl-its-umich-edu/student_explorer/blob/develop/student_explorer/templates/student_explorer/about.html) page needs to be updated.

My suggestion is to update the hard coded value for now without any configuration design changes.

**Comment by jonespm** [comment]
We already have an mcommunity group here. I don't think we need to mention who the specific service manager is. I think if we wanted to do that it would be better to have it on the documentation page and link to that, but I don't see it mentioned there either.

https://documentation.its.umich.edu/student-explorer-general

Yeah, ideally this would be configurable or flatpages but it doesn't change much.

**Comment by zqian** [comment]
It is much easier to update [https://documentation.its.umich.edu/student-explorer-general](https://documentation.its.umich.edu/student-explorer-general) than making changes to github.

So we will remove the mention of Service Manager altogether here.

**Comment by HemanginiShah-zz** [comment]
Yes, I am OK as long as the reference of Maggie's name is removed.  Since she is getting all inquiries/questions email form campus users as they are learning about the going away of Student Explorer in near future.
