### ISSUE TITLE
yum and yum-utils have been removed, need to replace these

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#253]
[yum and yum-utils have been removed ](https://askubuntu.com/a/1226145
)from the image because they relied on python 2. We need to replace the Oracle client install with different steps. 

It looks like they can be downloaded directly now and converted which wasn't an option 2 years ago.

**Comment by jonespm** [comment]
This will be QA'd just be seeing if the app can connect to Oracle. If it can't most things like viewing students and classes won't work.

**Comment by zqian** [comment]
tested the Oracle connection with Student Explorer test server
