### ISSUE TITLE
Add announcement area/banner using a flatpage

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/student_explorer#268]
We're going to need to communicate with users periodically during 2023 about the state of the application, and we've received a request to add an announcement banner, something similar to what is currently in Remote Office Hours Queue.

**Comment by HemanginiShah-zz** [comment]
Communicate to SE campus users: 
Canvas data UDW will be stopped supporting toward the end of the year.. UDW will be there but no update to it. Unizin advises UDW users to switch to UDP.  Unizin is planning to roll out canvas data in fall.
Create a banner on the SE app home page: SE will not be receiving new data (refreshed data) beyond December 2023.
