### ISSUE TITLE
Update Node, MySQL sources/images to get application to build and run locally

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/student_explorer#269]
I had some trouble getting the application to build as is. Looks like it's facing some of the `bookworm`-related issues some of our other applications are. Node is at 16, which will reach end of life in October. Python 3.8 is still supported as a maintenance release. I'm not sure the `nodesource` approach we were using is working, and there's an error when pulling the `mysql` image. This may also be an opportunity to resolve any reported library vulnerabilities. Goal should be to make the minimum number of changes to get things running and supported.

Note: Updating this, I was running off of `master` not `develop`.

**Comment by zqian** [comment]
No issue found related to those upgrades with basic testings.
