### ISSUE TITLE
adding GA4 support

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#272]
We need to adapt the SE tool for the recent GA4 upgrade

**Comment by HemanginiShah-zz** [comment]
Google Analytics Error message while accessing GA4 for SE.
![image](https://github.com/tl-its-umich-edu/student_explorer/assets/29413657/1f1a4581-0c9e-4151-8218-65c0d1e59da4)

**Comment by HemanginiShah-zz** [comment]
The Student Explorer data need to be analyzed through Google Analytics 4 by setting up appropriately to track userid, session time, pages visited etc.
