### ISSUE TITLE
Add daily cron job support for checking advisor Canvas membership

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student_explorer#41]
Need to implement daily cron job to do the following routine, which is captured in issue_11. 

- [x] iterate through advisor list in Student Explorer database, and select those affiliated with Athletic department #43 
- [x] for those athletic department advisors, find out their students and associated courses
- [x] verifies that those advisor has been added to his/her student Canvas sites as observer role, if not, add the advisor to Canvas site as observer
- [x] inside the SE course detail view, add in a link as "Observe student in Canvas site" with the url to Canvas course site

- [ ] Add a timestamp to both the logs and the table. (Maybe look at the MyLA logging block, the cron there has the timestamp https://github.com/tl-its-umich-edu/my-learning-analytics/blob/924a2ca60a6ab0cb0137750b3c1dfd7eac1ec79e/dashboard/settings.py#L185)
- [ ] If they're not in affiliated department print the department they were detected to be in to the logs. Might also want to print a debug message for when they are found in the table lookup
- [ ] Change uniquename to uniqname

**Comment by burgess66** [comment]
Is there a way to hide the "Observe student in Canvas site" link for all but athletic advisors?
If this displays for all users, that is going to be a problem; most users will not be able to use the link.

**Comment by burgess66** [comment]
Math 116 data is provided via the LMS the Math dept uses: [WebWorK](https://instruct.math.lsa.umich.edu/webwork2).  The link that is being constructed for the Canvas course is invalid.

**Comment by burgess66** [comment]
When we first scoped out the work for this with Gonzalo, we discussed having the advisor trigger the action of being added to the course site as a observer.  With this add via a batch process, that may cause issues because more students may have advisors as observers than is necessary (maybe not all students have to be closely watched by their advisor).

 I want to discuss this with the athletic advisor (and working with our new Service Manager, Maggie)
before we go further with this approach.

**Comment by zqian** [comment]
OK. Let us know if the cron job is not desired.

**Comment by DanielDugan** [comment]
Is there a way to hide the "Observe student in Canvas site" link for all but athletic advisors?

You would need to make changes to the user model to only display that link for athletic advisors.
It can be done.
https://docs.djangoproject.com/en/2.1/ref/contrib/auth/
