### ISSUE TITLE
Student Explorer data purged after semester ends

### ISSUE THREAD

**Issue by DanielDugan** [tl-its-umich-edu/student_explorer#53]
Dear Dan and IT Help folks, 

Request:  It appears that Student Explorer data from the Fall term has been purged in advance of the beginning of the Winter term.  For the future, we would like to request that data in the Student Explorer application from the previous term be retained a little longer --  until the day before the start of the next term.  

Rationale:  After grades are posted at the end of each term, the LSA Academic Standards Board conducts our grade review to determine whether students should be placed on academic probation, be returned to good academic standing, or (in extreme cases) suspended.  In borderline cases, we would find it very helpful to be able to take at a look at a student's Student Explorer data to see the details of their class participation and grades in class assignments.  

Please feel free to contact me if you need further information about this request.  

Thanks in advance for your help and consideration. 

Best regards,
Phil

**Comment by jonespm** [comment]
This is being resolved by IQ to retain the data for longer

**Comment by mfldavidson** [comment]
Resolved by IQ 2/28/19
