### ISSUE TITLE
Current page status indicator showing above footer

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#59]
On lists that go onto multiple pages, the status indicator showing the page number the user is on is showing above the footer. This issue can be seen on [the page for advisors with more than 1 page of students in their cohort](https://studentexplorer.ai.umich.edu/advisors/kerriw/), as well as [the admin manage users page](https://studentexplorer.ai.umich.edu/manage/users/). Minor but wanted to get it in the backlog as a known issue.

![image](https://user-images.githubusercontent.com/31591389/51491508-87065480-1d7c-11e9-954a-c41a7f9177cd.png)

![image](https://user-images.githubusercontent.com/31591389/51491790-76a2a980-1d7d-11e9-8239-e0275811c745.png)

**Comment by jonespm** [comment]
It seems like the problem might be the z-index in student_explorer/static/bootstrap/less/pagination.less is set for this element. Maybe the footer should have a higher z-index rather than lowering this one?

**Comment by zqian** [comment]
@mfldavidson please test this on dev server
