### ISSUE TITLE
Make Student Explorer logo link to the "homepage"

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#62]
It is [standard practice in UX](https://www.nngroup.com/articles/homepage-links/) for a logo to be in the upper left of the page (done, we've got that), visually distinct from other items (could be more distinct, but good enough for now), and link to the homepage. Currently, the logo is not a link at all and takes you nowhere, violating a user's expectations. I am wondering if we can make clicking on the logo behave the same way as going to https://studentexplorer.ai.umich.edu -- that is, go to the "My Students" page if the user has a cohort, or otherwise redirect to /advisors

**Comment by zqian** [comment]
@mfldavidson please test this on [SE dev server](https://dev.studentexplorer.openshift.dsc.umich.edu/)

**Comment by mfldavidson** [comment]
Looks perfect. I've tested in every way I know how and it is behaving as it should. @zqian Would the preference be for me to change the status of this issue to note that it is closed, move it to done in the project, or something else?
