### ISSUE TITLE
Add link in header to ITS Documentation for Student Explorer

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#68]
To address issues mentioned by advisors in meetings with T&L staff as well as found in research by UMSI regarding lack of training around or understanding of Student Explorer for advisors when they first get access, I would like to propose this "quick fix" of adding an external link in the header that takes the user to the [ITS Documentation on Student Explorer](https://documentation.its.umich.edu/node/831).

Link should be in the header to the right of "Advisors" and have an external link icon (in the same color as the text) immediately to the right. External link icon like [this](https://www.flaticon.com/free-icon/external-link-symbol_25284) but not necessarily the same one. Not sure if we already use an icon library--if so, we can just use the external link icon from there. If not, I can throw one together real quick, just let me know.

Rough mock-up:
![mockup-resources-support-ext-link](https://user-images.githubusercontent.com/31591389/51858477-d1e71580-2302-11e9-8b40-d849809f8a64.png)

**Comment by zqian** [comment]
@mfldavidson please test this on [SE dev server](https://dev.studentexplorer.openshift.dsc.umich.edu/)
