### ISSUE TITLE
Search by more than just 1 word

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#83]
Advisors sometimes don't have readily available the uniqname or UMID of the student they want to look up in Student Explorer, so they need to search by the student's name. However, SE appears to only search the first word up until a space, which makes it challenging for advisors to find the right student.

For example, searching for `Maggie Davidson` returns a list of every student with the string "Maggie" anywhere in their first, last, or uniqname, in alphabetical order by last name (searching just for `Maggie` returns the exact same results). Searching for variants such as `"Maggie Davidson"` or `Maggie+Davidson` return no results. Searching for `Davidson` returns every student with the string "Davidson" anywhere in their first, last, or uniqname, but in a totally random order (within those that have last name of only "Davidson") presumably because the only sort set is by last name, and there is no secondary sort, so if they all have the same last name it just appears random.

I would like to explore options to improve this search behavior so that if an advisor searches `Maggie Davidson`, only the student with both "Maggie" and "Davidson" in their name would be returned.

I am still understanding the impact of this issue.

Original source: Katrina at Ross

**Comment by jonespm** [comment]
The code this is using in the backend is using a relatively simple [icontains](https://github.com/tl-its-umich-edu/student_explorer/blob/4472bff9d355e943d1de5bbb9225b5c358bc4538/seumich/views.py#L116) for each value split on a space. So this is why searching "Maggie Davidson" would search for anything matching maggie or davidson (case insensitive).

We could change this to not do a split, I don't think it should be doing this anyway, so 'Maggie Davidson' only matches exactly that. While "Maggie" would still match anything. 

I can't think of any cases where this split would be useful or result in expected matches?

**Comment by jonespm** [comment]
Okay, I kind of see why the split was done. In the database there are two columns, FSTDNT_PREF_FIRST_NM and STDNT_PREF_SURNM. If you have a full name like "Maggie Davidson" it won't find it at all. . . 

So we're probably going to either to [concat](https://docs.djangoproject.com/en/1.8/ref/models/database-functions/#concat) on this and use that.

**Comment by mfldavidson** [comment]
b-e-a-UTIFUL work. I have tested to my heart's content.
