### ISSUE TITLE
Add more detailed text to /about

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#86]
There is an /about route, but it is out of date and minimal. I would like to make use of this path to provide users with information about the tool that is more informational and not help-related, and keep informational stuff out of the ITS Documentation.

I am eventually hoping we can make this a page that does not require authentication and that users can see and get redirected to instead of the [403 error.](https://github.com/tl-its-umich-edu/student_explorer/blob/develop/student_explorer/templates/403.html)

Text for page:

### About Student Explorer
Student Explorer is an early warning system that leverages Learning Management System data to **help academic advisors identify at-risk students.** It uses learning analytics techniques to create actionable intelligence that assists academic advisors in identifying students at risk of academic jeopardy in order to facilitate outreach to these students. The tool helps advisors create timely interventions to direct students toward resources or behavioral changes that help facilitate future student success. Student Explorer is available to **all academic advisors at the U-M Ann Arbor campus upon request for access** and includes information about **all students on the Ann Arbor campus, including graduate students**. For more information about how Student Explorer works and how to use it, please refer to the [Student Explorer documentation.](https://documentation.its.umich.edu/node/831)

### About Cohorts
Student Explorer operates using a cohort model; students are assigned to advisors using cohorts so that advisors can see all of their students in their ["My Students" tab.](https://studentexplorer.ai.umich.edu) **You do not need to have cohorts in order to use Student Explorer**--you can search for students individually using the search bar in the upper right, or navigate to an individual student's page using the link under "Term Progress" in the LSA Undergraduate Student Advising File. However, if you would like to set up a cohort to see all of your students in one list, please follow the instructions in the [Student Explorer documentation.](https://documentation.its.umich.edu/node/831) **Cohorts are not connected to advisor assignments in Wolverine Access or the LSA Undergraduate Student Advising File.**

### Student Explorer History
Student Explorer was started as a research project in 2011 led by Professor Stephanie Teasley and Dr. Steven Lonn in partnership with M-STEM Academies. LSA Technology Services, Academic Innovation, and ITS Teaching & Learning have contributed to the design, development, and management of the tool. Student Explorer is currently run by ITS Teaching & Learning and **questions and comments can be directed to the team by [submitting feedback.](https://studentexplorer.ai.umich.edu/feedback/)**

**Comment by mfldavidson** [comment]
Addition to add after line 37 `<hr/>` before line 38 `<p>Build Name:`

## Technical Information
[The GitHub repository](https://github.com/tl-its-umich-edu/student_explorer) for Student Explorer is public. [View release notes](https://github.com/tl-its-umich-edu/student_explorer/releases) for Student Explorer.

**Comment by mfldavidson** [comment]
Using [this Google Doc](https://docs.google.com/document/d/1hKjDdliEdiFf5KDVATpp_aC9MqKYGfVcIvRgTiTHqpo/edit?ts=5d83e8e7) to work through all changes above "Technical Information." Currently ready to go.

**Comment by ssciolla** [comment]
Issue was resolved, and the fix was QA tested.
