### ISSUE TITLE
Remove CTools text from "Weekly Activity" viz

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/student_explorer#99]
Since we don't source data from CTools anymore, we should change the descriptive text that goes with the Weekly Activity visualization from:
`This graph shows the percentile ranking of the student's page views (Canvas) or log-ins (CTools).`
to:
`This graph shows the percentile ranking of the student's page views in Canvas as compared to other students in the course (note that page view data is not available for data sourced from the Math Department)`

**Comment by jonespm** [comment]
Hmm is that math department addendum ever likely to change? Does this apply to Math courses in Canvas? Do people know what this means?

**Comment by zqian** [comment]
Matt is not using Canvas for their assignments or tests. They want to proctor assignment or quizzes, using the WeBWork frame work. 

This won't change in the near future.

**Comment by mfldavidson** [comment]
Just in case they ever do, I wonder if we should change it to something like "note that page view data is not available if the Data Source identified at the top of this page is MathDept" OR (even better) only show the Weekly Activity viz if Data Source is not MathDept

**Comment by jonespm** [comment]
I feel like as an end user I'd just be confused if it singled out a single department like this. I'm also looking at a student in a math course (MATH 214) and the weekly activity is populated but the cumulative score isn't populated. If you had something generic like "(Note page view data may not be available for departments that don't use Canvas)" seems more useful? 

I feel like it should be more dynamic, if there's no data just don't show the graph? This is a different feature though. Removing CTools makes complete sense though. Maybe I'll have to see what you mean here.

**Comment by zqian** [comment]
Based on email discussion, we suggest the text to be changed into:

This graph shows the percentile ranking of the student's page views in Canvas as compared to other students in the course (note that activity data is not available for courses without Canvas activity, common for MATH courses)

**Comment by mfldavidson** [comment]
I agree with this and will make the change
